# Generated by Django 2.2.1 on 2019-06-17 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medical_Record',
            fields=[
                ('ETR_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('medical_id', models.CharField(max_length=200)),
                ('smoking', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('NI', 'No Information')], max_length=3)),
                ('smoking_comments', models.TextField()),
                ('diabetes', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('NI', 'No Information')], max_length=3)),
                ('diabetes_comments', models.TextField()),
                ('ocular_disease', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('NI', 'No Information')], max_length=3)),
                ('ocular_disease_comments', models.TextField()),
                ('amd', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('NI', 'No Information')], max_length=3)),
                ('amd_comments', models.TextField()),
                ('cod', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('NI', 'No Information')], max_length=3)),
                ('cod_comments', models.TextField()),
                ('ethnicity', models.TextField()),
                ('medication', models.TextField()),
                ('additional_notes', models.TextField()),
            ],
        ),
    ]
