# Generated by Django 2.2.2 on 2019-06-24 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medical_record',
            old_name='amd',
            new_name='AMD',
        ),
        migrations.RenameField(
            model_name='medical_record',
            old_name='cod',
            new_name='COD',
        ),
        migrations.RemoveField(
            model_name='medical_record',
            name='amd_comments',
        ),
        migrations.RemoveField(
            model_name='medical_record',
            name='cod_comments',
        ),
        migrations.AddField(
            model_name='medical_record',
            name='AMD_comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='medical_record',
            name='COD_comments',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='medical_record',
            name='additional_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='medical_record',
            name='diabetes_comments',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='medical_record',
            name='ethnicity',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='medical_record',
            name='medication',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='medical_record',
            name='ocular_disease_comments',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='medical_record',
            name='smoking_comments',
            field=models.TextField(blank=True),
        ),
    ]
