# Generated by Django 2.2.2 on 2019-07-03 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190624_1103'),
    ]

    operations = [
        migrations.CreateModel(
            name='haplotypes',
            fields=[
                ('ETR_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('haplotype1', models.CharField(max_length=200)),
                ('haplotype2', models.CharField(max_length=200)),
                ('probability', models.FloatField(blank=True)),
                ('likelihood', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
            ],
        ),
    ]
