# Generated by Django 2.2.2 on 2019-07-03 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_haplotypes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='haplotypes',
            options={'verbose_name_plural': 'Haplotypes'},
        ),
        migrations.AlterModelOptions(
            name='medical_record',
            options={'verbose_name_plural': 'Medical Records'},
        ),
        migrations.RenameField(
            model_name='haplotypes',
            old_name='likelihood',
            new_name='Most_likely_haplotype',
        ),
        migrations.RenameField(
            model_name='haplotypes',
            old_name='haplotype1',
            new_name='haplotype_1',
        ),
        migrations.RenameField(
            model_name='haplotypes',
            old_name='haplotype2',
            new_name='haplotype_2',
        ),
        migrations.AlterField(
            model_name='haplotypes',
            name='probability',
            field=models.CharField(max_length=200),
        ),
    ]
