# Generated by Django 2.2.2 on 2019-07-09 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190703_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='haplotypes',
            name='Most_likely_haplotype',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3),
        ),
    ]
