# Generated by Django 2.2.2 on 2019-07-13 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20190709_2304'),
    ]

    operations = [
        migrations.CreateModel(
            name='genotypes',
            fields=[
                ('ETR_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('ARMS2', models.CharField(max_length=3)),
                ('HTRA1', models.CharField(max_length=3)),
                ('Risk', models.CharField(blank=True, choices=[('No Risk', 'No Risk'), ('Heterozygous Risk', 'Heterozygous Risk'), ('Homozygous Risk', 'Homozygous Risk'), ('Not Complete', 'Not Complete')], max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Genotypes',
            },
        ),
    ]
