# Generated by Django 2.2.2 on 2019-07-18 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_genotypes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('ETR_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('SEX', models.CharField(blank=True, choices=[('F', 'F'), ('M', 'M'), ('NI', 'No Information')], max_length=14)),
                ('AGE', models.IntegerField(blank=True)),
                ('date_processed', models.DateTimeField(blank=True)),
                ('pm_time', models.IntegerField(blank=True)),
                ('AMD', models.CharField(choices=[('No', 'No'), ('Early', 'Early'), ('Borderline', 'Borderline'), ('Late', 'Late'), ('Wet', 'Wet'), ('Unknown', 'Unknown'), ('Not Clincial', 'Not Clincial'), ('Non Control', 'Non Control')], max_length=3)),
                ('AMD_comments', models.TextField(blank=True)),
                ('image_file', models.CharField(blank=True, max_length=100)),
                ('ICB_R', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('ICB_L', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('LENS_R', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('LENS_L', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('mac_BM', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('mac_biopsy', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('NSR_R', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('NSR_L', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('RET_BM_R', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('RET_BM_L', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('ret_biopsy', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('SCLERA_R', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('SCLERA_L', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('VITREOUS_R', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('VITEROUS_L', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('optic_nerve', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('DNA_Banked', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('ICB_Genotyped', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('Paul_Bisop', models.TextField(blank=True)),
                ('comments', models.TextField(blank=True)),
                ('other', models.TextField(blank=True)),
                ('smoking', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('NI', 'No Information')], max_length=3)),
                ('smoking_comments', models.TextField(blank=True)),
                ('diabetes', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('NI', 'No Information')], max_length=3)),
                ('diabetes_comments', models.TextField(blank=True)),
                ('ocular_disease', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('NI', 'No Information')], max_length=3)),
                ('ocular_disease_comments', models.TextField(blank=True)),
                ('COD', models.CharField(choices=[('Known', 'Known'), ('Unknown', 'Unknown')], max_length=3)),
                ('COD_comments', models.TextField(blank=True)),
                ('medication', models.TextField(blank=True)),
                ('ethnicity', models.TextField(blank=True)),
                ('additional_notes', models.TextField(blank=True)),
                ('ARMS2', models.CharField(blank=True, max_length=3)),
                ('HTRA1', models.CharField(blank=True, max_length=3)),
                ('Risk', models.CharField(blank=True, choices=[('No Risk', 'No Risk'), ('Heterozygous Risk', 'Heterozygous Risk'), ('Homozygous Risk', 'Homozygous Risk'), ('Not Complete', 'Not Complete')], max_length=100)),
                ('haplotype_1', models.CharField(max_length=200)),
                ('haplotype_2', models.CharField(max_length=200)),
                ('probability', models.CharField(max_length=200)),
                ('Most_likely_haplotype', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
            ],
            options={
                'verbose_name_plural': 'Records',
            },
        ),
        migrations.AlterField(
            model_name='genotypes',
            name='ARMS2',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AlterField(
            model_name='genotypes',
            name='HTRA1',
            field=models.CharField(blank=True, max_length=3),
        ),
    ]
