# Generated by Django 2.2.2 on 2019-07-19 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20190718_1018'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='VITEROUS_L',
            new_name='VITREOUS_L',
        ),
    ]
