# Generated by Django 2.2.2 on 2019-07-19 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20190719_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='ICB_R',
            field=models.CharField(max_length=3),
        ),
    ]
