# Generated by Django 2.2.2 on 2019-07-25 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20190723_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='location_1',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AddField(
            model_name='record',
            name='location_2',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AddField(
            model_name='record',
            name='location_3',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AddField(
            model_name='record',
            name='location_4',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AddField(
            model_name='record',
            name='tissue_1',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AddField(
            model_name='record',
            name='tissue_2',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AddField(
            model_name='record',
            name='tissue_3',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AddField(
            model_name='record',
            name='tissue_4',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
