# Generated by Django 2.2.2 on 2019-07-25 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20190725_1232'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='location_1',
            new_name='Location_1',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='location_2',
            new_name='Location_2',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='location_3',
            new_name='Location_3',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='location_4',
            new_name='Location_4',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='tissue_1',
            new_name='Tissue_1',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='tissue_2',
            new_name='Tissue_2',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='tissue_3',
            new_name='Tissue_3',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='tissue_4',
            new_name='Tissue_4',
        ),
    ]
