# Generated by Django 2.2.2 on 2019-08-02 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20190725_1236'),
    ]

    operations = [
        migrations.DeleteModel(
            name='genotypes',
        ),
        migrations.DeleteModel(
            name='haplotypes',
        ),
        migrations.DeleteModel(
            name='Medical_Record',
        ),
    ]
