# Generated by Django 2.2.2 on 2019-08-03 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20190802_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='ICB_R',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3),
        ),
    ]
