# Generated by Django 2.2.2 on 2019-08-04 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20190803_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='ICB_R',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3),
        ),
    ]
