# Generated by Django 2.2.2 on 2019-08-04 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20190804_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='AMD',
            field=models.CharField(choices=[('No', 'No'), ('Early', 'Early'), ('Borderline', 'Borderline'), ('Late', 'Late'), ('Wet', 'Wet'), ('Unknown', 'Unknown'), ('Not Clincial', 'Not Clincial'), ('Non Control', 'Non Control')], max_length=15),
        ),
    ]
