# Generated by Django 2.2.2 on 2019-09-04 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20190904_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='RNA_seq',
            field=models.TextField(blank=True),
        ),
    ]
